project:
  type: website
  output-dir: docs

website:
  title: "Jessica Hampton"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
      - href: events.qmd
      - href: scholarship.qmd
      - href: ecosophy.qmd
      - href: Teaching.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



