---
title: "Publications & Talks"
---

### Publications

-   Hampton, J. (due 2027) **Ecolinguistics and Endangered Languages. Emplacing ecological wisdom through language revitalisation**. A monograph due to feature in Bloomsbury Advances in Ecolinguistics. <https://www.bloomsbury.com/uk/series/bloomsbury-advances-in-ecolinguistics/>

-   **Hampton, J.** & Buckingham, D. (2026) '**Redefining language, identity, and heritage through an ecolinguistic lens.'** In R.Poole, D. F. Virdis, **J.** **Hampton**, & A. Ghorbanpour (eds.), *The Bloomsbury Handbook of Ecolinguistics***.** Bloomsbury.

-   Poole, R., Virdis, D. F., **Hampton, J**. & Ghorbanpour, A. (eds.) (2026) **The Bloomsbury Handbook of Ecolinguistics.** Bloomsbury.

-   Coretta, S., De Cia, S. & **Hampton, J.** (2025) **A vitality assessment of Gallo-Romance of Northern Italy.** Pre-print available at <https://osf.io/fuzby_v1/>

-   Guardamagna, C., **Hampton, J.**, Roccia, M. & Sredanovic, D. (2025) **“Where are you from?”: re-examining national identity and microaggressions in context.** Modern Languages Open. Pre-print available at <https://doi.org/10.31219/osf.io/8dmrg_v1>

-   Hampton, J. (2025) **‘From global connections to local roots: exploring language ideologies in Emilian and Esperanto for language revitalisation.’** In A. Ajšić & R. Vessey (eds.), *Current Approaches to Language Ideology and Metalinguistic Discourse*. Routledge. <https://www.routledge.com/Current-Approaches-to-Language-Ideology-and-Metalinguistic-Discourse/Ajsic-Vessey/p/book/9781032786667>

-   Hampton, J. (2025) Ó Ceallaigh, Ben (2022): **Neoliberalism and Language Shift. Lessons from the Republic of Ireland Post-2008**. De Gruyer. 278 p. Sociolinguistic Studies. \[Book review\]

-   **Hampton, J.** & Coretta, S. (2024) **Language practices of Emilian and Esperanto communities: spaces of use, explicit language attitudes and self-reported competence**. Journal of Multilingual and Multicultural Development, 1–26. <https://doi.org/10.1080/01434632.2024.2413933>

-   Guardamagna, C., **Hampton, J.**, Roccia, M. & Sredanovic, D. (2024) **Microagressions and Impoliteness at the crossroad: EU academics in the UK facing hostility in the Brexit age**. Journal of Language Aggression and Conflict. <https://doi.org/10.1075/jlac.00113.gua>

-   Ioppolo, R., **Hampton, J.**, Abel, L., Etheridge & M., Tal-Perry, N. (2024). **Exploring the use of Resume for Research and Innovation Narrative CVs in live postdoc recruitments**. <https://doi.org/10.17605/OSF.IO/GWA9R>

-   Hampton, J. (2023). **"wRapping" traditions into modernity: the negotiation of Emilian and Esperanto identities in YouTube rap songs**. Modern Languages Open. <https://doi.org/10.3828/mlo.v0i0.449>

-   Hampton, J. (2023). **Measuring attitudes: Adopting triangulation as an attempt to square the circle. Swipe up for more**. Modern Languages Open. <http://dx.doi.org/10.3828/mlo.v0i0.450>

-   Hampton, J. (2023). Devilla, Lorenzo and Galiñanes Gallén, Marta (eds.) (2021): **Lingue minori e turismo. Aspetti linguistici, sociolinguistici e territoriali** \[Minority languages and tourism. Linguistic, sociolinguistic and territorial aspects\]. Cagliari: Arkadia. 128 p. Sociolinguistica, vol. 37, no. 1, 2023, pp. 115-144. \[Book review\]. <https://doi.org/10.1515/soci-2023-0001>

-   Hampton, J. (2022). **Telling stories of the local natural world: a path of reconnection with language and place in the Emilian context**. Journal of World Languages. <https://doi.org/10.1515/jwl-2022-0006>

-   Roccia, M. & **Hampton, J.** (2021). **The Stories We Live By and the stories we won't stand by: Measuring the impact of a free online course in ecolinguistics**. Journal of World Languages, 7(1), 58-79. <https://doi.org/10.1515/jwl-2021-0004>

-   De Cia, S. & **Hampton, J.** (2020). **Debunking Rhaeto-Romance: Synchronic Evidence from Two Peripheral Northern Italian Dialects**. Modern Languages Open, 7 pp. 1-18. DOI: <https://doi.org/10.3828/mlo.v0i0.309>

### Edited Special Issues

-   Tufi, S. & **Hampton, J.** (2026) Borderscapes - The de/construction of borders as an everyday practice, Issue 3, Vol 47. *Journal of Intercultural Studies.*

-   Guardamagna, C., **Hampton, J.**, Roccia, M. & Sredanovic, D. (forthcoming) Navigating Language, Identity and Belonging: Migration Experiences in Post-Brexit Europe. *Modern Languages Open*

### Invited Talks

-   October 2025 — University of Vienna, Austria: **Into the In-Between: towards a methodology for exploring the transformative potential of Indigenous language concepts for decolonising Linguistic Landscape studies** <https://wsg.univie.ac.at/veranstaltungen/jessica-hampton-into-the-in-between-towards-a-methodology-for-exploring-the-transformative-potential-of-indigenous-language-concepts-for-decolonising-linguistic-landscape-studies/?mc_id=61>

-   September 2025 — University College Dublin: **Telling stories of the local natural world: A path of reconnection with language and place in the Emilian context** Funded by SIS Networking Scheme <https://italianstudies.org.uk/current-research/post-doctoral-research/>

-   December 2024 -- Panelist on 6 Seconds Webinar "**Educate the Language: the stories we live by**"

    The words we choose deeply influence how we feel, how we connect with others, and ultimately, how we act. In this webinar, we will explore the relationship between language and emotions, reflecting on their impact on society and how they shape our present and future. We will also introduce The Stories We Live By, a free ecolinguistics course offered by the University of Gloucestershire and featured on the UNSDG Learn platform. Join us to discover how language can become a tool for transformation toward a more sustainable and conscious future. <https://events.6seconds.org/event/NTA4MQ==>

-   May 2023 -- British Academy, London. **Applying mixed methodologies**.

-   March 2022 -- University of Edinburgh: **Invited lecture on diary as a research method**.

### Talks

-   September 2025 — AMLI 2025, Hope University, Liverpool: **Deviance and Belonging: Transgressing the Borders of Italianness in Migration** <https://store.hope.ac.uk/conferences-and-events/faculty-of-creative-arts-and-humanities/events/approaches-to-migration-language-and-identity-conference-2025>

-   September 2025 — LL16, Essen, Germany: **Signs of survival: the role of endangered languages in the Linguistic Landscape of crises** <https://www.ll16-ude.de/program/>

-   June 2025 — SIEF 2025, Aberdeen: **Into the In-Between: towards a methodology for exploring the transformative potential of Indigenous language concepts for decolonising Linguistic Landscape studies** <https://www.siefhome.org/congresses/sief2025/programme#timetable>

-   May 2025 — Postgraduates' and Fellows' St Catharine's Day seminar, University of Cambridge: **Decolonising Linguistic Landscape Studies** Slides available at <https://osf.io/pnfby/> [{{< fa cloud-arrow-down >}}](files/stcat.jpg)

-   May 2025 — Languages, Objects and Homes:Transnational Communities in Borderscapes, University of Liverpool: **Deviance and Belonging: Transgressing the Borders of Italianness in Migration** [{{< fa cloud-arrow-down >}}](files/borderscapes.pdf)

-   November 2024 -- ASMI Conference, Senate House, London: "**Telling stories of the local natural world: A path of reconnection with language and place in the Emilian context**".

-   November 2024 -- BAAL Social Justice Summit, online: "**Language, identity, belonging: analysing bordering practices in the construction of schoolscapes through an ecolinguistic lens**." <https://baalsocialjusticesig.weebly.com/events.html>

-   October 2024 -- Convegno Linguistic Landscape, Siena, Italy: "**Schoolscapes and the (de)construction of borders – two case studies**."

-   July 2024 -- CELC 10 Language Endangerment and Revitalisation: The decade ahead, University of Cambridge: "**Comparing language attitudes, use and competence in the northern Italian speech communities of Emilian and Veneto**." [{{< fa cloud-arrow-down >}}](files/Jess_Hampton_CELC10.pdf)

-   June 2024 -- Northern Englishes Workshop 10, University of Chester: "**Coming full circle: analysing bordering practices in the construction of schoolscapes through an ecolinguistic lens**."

-   June 2024 -- Linguistic Landscape 15, Wellington, New Zealand: "**Coming full circle: analysing bordering practices in the construction of schoolscapes through an ecolinguistic lens**."

-   May 2024 -- CLOW4 Warsaw, Poland: "**Comparing language attitudes, use and competence in the northern Italian speech communities of Emilian and Veneto**." [{{< fa cloud-arrow-down >}}](files/CLOW4.pdf)

-   June 2023 -- XIX International Conference on Minority Languages, University of Wales: "**Measuring spaces and observing attitudes: a comparative analysis on the vitality of Emilian and Esperanto**".

-   September 2022 -- Communicating Sustainability, University of Glasgow: "**Defining Sustainability: Data from a Cross-Government Hub for Climate Action**".

-   February 2022 -- Language, Power and Society, University of Kent: "**Telling stories of the natural world. A path to reconnection with language and place**".

-   October 2021 -- Languages in the Digital Age: Modern technologies for under-resourced languages, Tbilisi (online): "**Fieldwork notes and reflections on researching minoritized languages: drawing parallels between Emilian and Esperanto**".

-   May 2021 -- NEWCON2020 New Contexts for the Use of Minoritized Languages/Varieties, University of Zadar (online): "**Traumatic crises as revaluation opportunities for stigmatised varieties: Maintaining strength and sense of community with Emilian and Viennese**". \[Co-presented with Dr Barbara Soukup\]

-   April 2021 -- Memory, Heritage and Languages Symposium, University of Liverpool: "**Documenting Endangered Languages: A Tool to Conserve Heritage and Create Memories**".

-   May 2019 -- Rethinking Language and Community, University of Manchester: "**Rethinking Community: a lesson from Esperanto**".

-   November 2018 -- Citizens of Everywhere, University of Liverpool: "**Reframing citizenship to rediscover our place in the world**".

-   June 2018 -- Workshop on information structure, referential status and referent type in discourse and grammar, University of Manchester: "**Negation and Information Structure: the case of Modenese**".
