---
title: "Research & Scholarship"
---

::: {.callout-important title="Lighbulb Moments Exhibition" icon=false}

I was invited to contribute to this exciting exhibition for the University of Liverpool’s Victoria Gallery & Museum (VG&M) which celebrates some of the great ideas connected to the city of Liverpool. After visiting the Sydney Jones Special Collections & Archives, teaching materials for Esperanto and travel guides in Esperanto were selected to be displayed in the exhibition alongside a note on how research on this language can help us understand more about revitalising minoritised languages such as Emilian.

Read more about this exhibition here:
<https://news.liverpool.ac.uk/2025/07/10/tate-hall-reopens-with-a-new-exhibition-exploring-where-great-ideas-come-from/>


:::

::: {.callout-important title="Policy Change" icon=false}

Through ongoing collaborations with the Management School at the University of Liverpool, I helped steer Government guidance on how UK businesses should report
on methods to tackle modern slavery in their supply chains.

<https://www.liverpool.ac.uk/media/livacuk/schoolofmanagement/research/researchbrochure/ULMS-Research05.pdf>


:::

::: {.callout-important title="The Multilingual Picture Dataset-- MULTIPIC" icon=false}

Project Committe member and collaborator responsible for the Emilian language on this BA funded project led by Dr Christos Pliatsikas, Prof Marco Tamburelli, and Prof Jon Andoni Duñabeitia. 

Starting in April 2025 and running for four years, the project seeks to expand the current dataset by providing naming norms in eight under-represented languages, comprising: Scottish Gaelic, Cornish, Scotts, Alemannic, Lombard, Emilian, Silesian and Kashubian.

<https://research.reading.ac.uk/christos-lab/the-multilingual-picture-dataset-multipic/>


:::

::: {.callout-important title="Borderscapes Project" icon=false}

This is an AHRC funded project running from February 2024 to January 2025. I am the PDRA on Borderscapes, working alongside Prof Stefania Tufi (PI), Wendy O'Neill (RA), Emily Kearon-Warrilow (RA), our undegraduate research assistants, as well as the teachers and students at the four schools we've been collaborating with. <https://www.liverpool.ac.uk/languages-cultures-and-film/research/projects/borderscapes/>

As part of the project, students created their own piece of art (such as a drawing or a poem) depicting their environmental/cultural identity. These are showcased on our dedicated website created and curated by our wonderful Emily:
<https://borderscapes4.wixsite.com/digitalexhibition>
:::

::: {.callout-important title="EU Migrants Project" icon=false}

Since 2019, I have been working as a Research Assistant on this timely project led by Caterina Guardamagna at the University of Liverpool. We are a small, interdisciplinary team that also includes Djordje Sredanovic from the University of Chester and Mariana Roccia from the University of Gloucestershire and the International Ecolinguistics Association.

As part of this ongoing project, we interviewed around 40 Italian and Spanish academics based in the North West of England, merging our dataset with Djordje's to understand their migratory experience from a discursive perspective. Outputs include three articles (one in press at the time of writing and two ready to be submitted) and a symposium, whose proceedings are being prepared for a Special Issue and an edited volume.

More about our work can be found on our website <https://www.eumigrants.co.uk>

:::

::: {.callout-important title="Polentometro Project" icon=false}

In this project with Stefano Coretta and Simone De Cia, we are cconduting a first-of-its-kind survey of the vitality of the languages spoken in the north of Italy.

<https://www.soscisurvey.de/polentometro/>

:::

::: {.callout-tip title="International Ecolinguistics Association" icon=false}
-   Co-convenor   

-   Membership Officer 

-   Book Review Editor for *Language & Ecology*
<https://www.ecoling.net>

<https://www.ecolinguistics-association.org>

:::

::: {.callout-tip title="BAAL RICH SIG" icon=false}

-   Treasurer for BAAL RICH SIG

<https://richsig.wordpress.com>
:::


::: {.callout-tip title="University Council For Languages" icon=false}

-   2022-2025 Representative for Linguistics, Special Interest Group: Early Career Academics

<https://university-council-for-languages.org/early-career-academics/>
:::

